anonymous:
    anonymous_name: 'Anonymous User'
register:
    allow_account_creation: ''
    verification_email: ''
    password_strength: ''
    cancellation: ''
notifications: test@articlepulsehub.com
emails:
    account_creation: ''
    account_creation_message: ''
    account_activation: ''
    account_activation_message: ''
    password_recovery: ''
    password_recovery_message: ''
submit: 'Save Configuration'
