views_view_articles_listing_articles_lsting:
    title: 'Articles Lsting'
    path: /articles
    method:
        - GET
        - POST
        - PUT
        - OPTIONS
        - DELETE
        - ANY
    controller:
        class: Simp\Core\lib\controllers\ViewsController
        method: views_entry_controller
    access: ['administrator']
