views.view.articles.view.listing.articles:
    title: 'Listing Articles'
    path: /articles
    method:
        - GET
        - POST
        - PUT
        - OPTIONS
        - DELETE
        - ANY
    controller:
        class: Simp\Core\lib\controllers\ViewsController
        method: views_entry_controller
    access:
        - administrator
views.view.articles.view.article:
    title: Article
    path: '/article/[id:int]'
    method:
        - GET
        - POST
        - PUT
        - OPTIONS
        - DELETE
        - ANY
    controller:
        class: Simp\Core\lib\controllers\ViewsController
        method: views_entry_controller
    access:
        - administrator
