table:
  - CREATE TABLE IF NOT EXISTS `users` (
    `uid` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `mail` VARCHAR(255) NOT NULL,
    `status` BOOLEAN DEFAULT 0,
    `password` VARCHAR(255) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `login` TIMESTAMP NULL DEFAULT NULL
    )
  - CREATE TABLE IF NOT EXISTS `user_roles` (
    `rid` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `role_name` VARCHAR(255) NOT NULL,
    `role_label` VARCHAR(255) NOT NULL,
    `uid` INT NOT NULL,
    CONSTRAINT `fk_user_roles_uid` FOREIGN KEY (`uid`) REFERENCES `users` (`uid`) ON DELETE CASCADE
    )
  - CREATE TABLE IF NOT EXISTS `user_profile` (
    `pid` INT PRIMARY KEY AUTO_INCREMENT,
    `first_name` VARCHAR(255) NULL,
    `last_name` VARCHAR(255) NULL,
    `profile_image` INT NULL,
    `uid` INT NOT NULL,
    `description` TEXT NULL,
    `time_zone` VARCHAR(255) NULL,
    CONSTRAINT `fk_user_profile_uid` FOREIGN KEY (`uid`) REFERENCES `users` (`uid`) ON DELETE CASCADE
    )
