database.form.route:
  title: "Database Configuration Form"
  path: '/admin/configure/database'
  method:
    - GET
    - POST
  middleware:
    pre:
      - AdminMiddleware
    post:

  controller:
    class: Simp\Core\lib\controllers\DatabaseController
    method: database_form
home.page.route:
  title: "Home"
  path: ''
  method:
    - GET
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\HomeController
    method: home_controller

user.account.login.form.route:
  title: "Login"
  path: '/user/login'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: user_login_form_controller

user.account.google.redirect.route:
  title: "Google Redirect"
  path: '/user/oauth/google/access'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: user_login_google_redirect_controller

user.account.github.redirect.route:
  title: "Github Redirect"
  path: '/user/oauth/github/access'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: user_login_github_redirect_controller


user.account.logout.route:
  title: "Logout"
  path: '/user/logout'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: user_logout_controller


user.account.form.page.route:
  title: "Register"
  path: '/user/register'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\UserAccountFormController
    method: user_account_form_controller

system.messager.toastify:
  title: "Messages"
  path: '/system/messages'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: toastify_controller

system.people:
  title: "People"
  path: '/admin/people'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: people_controller

system.account.delete:
  title: "Account Deletion"
  path: '/user/[uid:int]/delete'
  method:
    - GET
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: account_delete_controller

system.account.edit:
  title: "Account Edit"
  path: '/user/[uid:int]/edit'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: account_edit_controller

system.account.view:
  title: "Account"
  path: '/user/[uid:int]'
  method:
    - GET
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: account_controller

system.account.profile.edit:
  title: "Profile Account Edit"
  path: '/user/[uid:int]/profile/edit'
  method:
    - GET
    - POST
  middleware:
    pre:

    post:

  controller:
    class: Simp\Core\lib\controllers\SystemController
    method: account_profile_edit_controller
