name: 'Listing Articles'
display_name: views.view.articles.view.listing.articles
response_type: text/html
content_type: all
template: ''
params: {  }
permission:
    - administrator
fields:
    node|title:
        field: title
        type: fields
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: node
    content_articles|content_articles_field_image:
        field: content_articles_field_image
        type: fields
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: content_articles
    node|created:
        field: created
        type: fields
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: node
    content_articles|content_articles_field_content_body:
        field: content_articles_field_content_body
        type: fields
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: content_articles
filter_criteria:
    node|status:
        field: status
        type: filter_criteria
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: node
    node|title:
        field: title
        type: filter_criteria
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: node
sort_criteria:
    node|created:
        field: created
        type: sort_criteria
        view: view.articles.view
        display: views.view.articles.view.listing.articles
        content_type: node
