name: 'Listing Articles'
display_name: views.view.articles.view.listing.articles
response_type: text/html
content_type: all
template: ''
params: {  }
permission:
    - administrator
fields:
    node:
        title:
            field: title
            type: fields
            view: view.articles.view
            display: views.view.articles.view.listing.articles
            content_type: node
            weight: 1
        created:
            field: created
            type: fields
            view: view.articles.view
            display: views.view.articles.view.listing.articles
            content_type: node
            weight: 3
    content_articles:
        content_articles_field_content_body:
            field: content_articles_field_content_body
            type: fields
            view: view.articles.view
            display: views.view.articles.view.listing.articles
            content_type: content_articles
            weight: 2
        content_articles_field_image:
            field: content_articles_field_image
            type: fields
            view: view.articles.view
            display: views.view.articles.view.listing.articles
            content_type: content_articles
            weight: 3
filter_criteria:
    bundle: all
    status: 'Yes'
sort_criteria:
    created: DESC
