name: 'Listing Articles'
display_name: views_view_prashant_listing_articles
response_type: text/html
content_type: all
template: ''
params:
    - ''
permission:
    - administrator
fields:
    node|title:
        field: title
        type: fields
        view: view_prashant
        display: views_view_prashant_listing_articles
        content_type: node
    node|created:
        field: created
        type: fields
        view: view_prashant
        display: views_view_prashant_listing_articles
        content_type: node
    content_articles|content_articles_field_content_body:
        field: content_articles_field_content_body
        type: fields
        view: view_prashant
        display: views_view_prashant_listing_articles
        content_type: content_articles
filter_criteria: {  }
sort_criteria:
    node|created:
        field: created
        type: sort_criteria
        view: view_prashant
        display: views_view_prashant_listing_articles
        content_type: node
        settings:
            order_in: DESC
            field: created
view: view_prashant
settings:
    default_empty: ''
    limit: '10'
    pagination: 'on'
    custom_params:
        - ''
    template_id: ''
    display_style: grid_rows
