name: Article
display_name: views.view.articles.view.article
response_type: text/html
content_type: all
template: ''
params:
    - id
permission:
    - administrator
fields:
    content_articles|content_articles_field_image:
        field: content_articles_field_image
        type: fields
        view: view.articles.view
        display: views.view.articles.view.article
        content_type: content_articles
    content_articles|content_articles_field_content_body:
        field: content_articles_field_content_body
        type: fields
        view: view.articles.view
        display: views.view.articles.view.article
        content_type: content_articles
filter_criteria: {  }
sort_criteria: {  }
