name: Articles
description: 'This is articles content'
machine_name: articles
created: '2025-03-23 06:17 AM'
fields:
    articles_content:
        type: textarea
        label: Content
        required: true
        class:
            - form-control
            - editor
        default_value: ''
        id: field-content
        handler: Simp\Default\TextAreaField
        name: articles_content
        conditions: {  }
        settings:
            allowed_file_types:
                - ''
            allowed_file_size: ''
    articles_tags:
        type: text
        label: Tags
        required: true
        class:
            - form-control
        default_value: ''
        id: field-tags
        handler: Simp\Default\BasicField
        name: articles_tags
        conditions: {  }
        settings:
            allowed_file_types:
                - ''
            allowed_file_size: ''
    articles_image:
        type: file
        label: Image
        required: true
        class:
            - form-control
        default_value: ''
        id: field-image
        options:
            multiple: multiple
        handler: Simp\Default\FileField
        name: articles_image
        conditions: {  }
        settings:
            allowed_file_types:
                - 'image/*'
            allowed_file_size: '4000000'
display_setting:
    articles_content:
        display_label: null
        display_as: p
        display_enabled: '1'
    articles_tags:
        display_label: null
        display_as: h6
        display_enabled: '1'
    articles_image:
        display_label: null
        display_as: image
        display_enabled: '1'
permission:
    - administrator
    - authenticated
    - manager
    - content_creator
    - anonymous
storage:
    - node__articles_content
    - node__articles_tags
    - node__articles_image
