articles:
    name: Articles
    description: 'this is content type for creating and managing articles data'
    machine_name: articles
    created: '2025-03-15 16:25 PM'
    fields:
        articles_content:
            type: textarea
            label: Content
            required: true
            class:
                - form-control
            default_value: ''
            id: content
            handler: Simp\Default\TextAreaField
            name: articles_content
        articles_image:
            type: file
            label: Image
            required: true
            class:
                - form-control
            default_value: ''
            id: image
            handler: Simp\Default\FileField
            name: articles_image
        articles_meta_information:
            type: details
            label: 'Meta Information'
            required: false
            class:
                - form-control
            default_value: ''
            id: meta-info
            options:
                open: open
            handler: Simp\Default\DetailWrapperField
            inner_field:
                articles_meta_title:
                    type: text
                    label: 'Meta Title'
                    required: false
                    class:
                        - form-control
                    default_value: ''
                    id: title-meta
                    handler: Simp\Default\BasicField
                    name: articles_meta_title
                articles_meta_description:
                    type: textarea
                    label: 'Meta Description'
                    required: false
                    class:
                        - form-control
                    default_value: ''
                    id: meta-description
                    handler: Simp\Default\TextAreaField
                    name: articles_meta_description
                articles_meta_image:
                    type: file
                    label: 'Meta Image'
                    required: false
                    class:
                        - form-control
                    default_value: ''
                    id: title-image
                    handler: Simp\Default\FileField
                    name: articles_meta_image
            name: articles_meta_information
    storage:
        - node__articles_content
        - node__articles_image
        - node__articles_meta_title
        - node__articles_meta_description
        - node__articles_meta_image
basic_page:
    name: 'Basic page'
    description: 'basic page content type'
    machine_name: basic_page
    created: '2025-03-16 15:44 PM'
    fields:
        basic_page_body:
            type: textarea
            label: Body
            required: false
            class:
                - form-control
            default_value: ''
            id: body
            handler: Simp\Default\TextAreaField
            name: basic_page_body
    storage:
        - node__basic_page_body
