name: Articles
description: 'this is articles content'
machine_name: content_articles
created: '2025-03-31 04:30 AM'
fields:
    content_articles_field_content_body:
        type: textarea
        label: 'Content Body'
        required: true
        class:
            - form-control
            - editor
            - textarea-editor
        default_value: ''
        id: field-content-body
        handler: Simp\Default\TextAreaField
        name: content_articles_field_content_body
        conditions: {  }
        settings:
            allowed_file_types:
                - ''
            allowed_file_size: ''
    content_articles_field_article_image:
        type: file
        label: 'Article image'
        required: true
        class:
            - form-control
        default_value: ''
        id: field-image
        handler: Simp\Default\FileField
        name: content_articles_field_article_image
        conditions: {  }
        settings:
            allowed_file_types:
                - 'image/*'
            allowed_file_size: '1000000'
        options:
            multple: multiple
display_setting:
    content_articles_field_content_body:
        display_label: null
        display_as: p
        display_enabled: '1'
    content_articles_field_article_image:
        display_label: null
        display_as: link
        display_enabled: '1'
permission:
    - administrator
    - authenticated
    - manager
    - content_creator
storage:
    - node__content_articles_field_content_body
    - node__content_articles_field_article_image
