name: Articles
description: 'This is articles contents store'
machine_name: content_articles
created: '2025-03-28 17:34 PM'
fields:
    content_articles_field_content_body:
        type: textarea
        label: 'Content Body'
        required: true
        class:
            - form-control
            - editor
            - textarea-editor
        default_value: ''
        id: field-content
        handler: Simp\Default\TextAreaField
        name: content_articles_field_content_body
        conditions: {  }
        settings:
            allowed_file_types:
                - ''
            allowed_file_size: ''
    content_articles_field_image:
        type: file
        label: Image
        required: true
        class:
            - form-control
        default_value: ''
        id: field-image
        handler: Simp\Default\FileField
        name: content_articles_field_image
        conditions: {  }
        settings:
            allowed_file_types:
                - 'image/*'
            allowed_file_size: '1000000'
display_setting: {  }
permission: {  }
storage:
    - node__content_articles_field_content_body
    - node__content_articles_field_image
