articles:
    name: Articles
    description: 'This is articles content type.'
    machine_name: articles
    created: '2025-03-17 05:13 AM'
    fields:
        articles_content:
            type: textarea
            label: Content
            required: true
            class:
                - form-control
                - textarea-editor
            default_value: ''
            id: content
            handler: Simp\Default\TextAreaField
            name: articles_content
            conditions:
                - ''
            settings:
                allowed_file_types:
                    - ''
                allowed_file_size: ''
        articles_image:
            type: file
            label: Image
            required: true
            class:
                - form-control
            default_value: ''
            id: field-image
            handler: Simp\Default\FileField
            conditions: {  }
            settings:
                allowed_file_types:
                    - 'image/*'
                allowed_file_size: '1000000'
            name: articles_image
        articles_meta_conditional_wrapper:
            type: conditional
            label: 'Meta Conditional Wrapper'
            required: false
            class:
                - form-control
            default_value: ''
            id: conditional-wrapper
            handler: Simp\Default\ConditionalField
            inner_field:
                articles_meta_title:
                    type: text
                    label: 'Meta Title'
                    required: false
                    class:
                        - form-control
                    default_value: ''
                    id: articles_meta_title
                    handler: Simp\Default\BasicField
                    name: articles_meta_title
                articles_meta_description:
                    type: textarea
                    label: 'Meta Description'
                    required: false
                    class:
                        - form-control
                    default_value: ''
                    id: articles_meta_description
                    handler: Simp\Default\TextAreaField
                    conditions:
                        - ''
                    settings:
                        allowed_file_types:
                            - ''
                        allowed_file_size: ''
                    name: articles_meta_description
                articles_meta_image:
                    type: file
                    label: 'Meta Image'
                    required: false
                    class:
                        - form-control
                    default_value: ''
                    id: meta-image
                    handler: Simp\Default\FileField
                    conditions: {  }
                    settings:
                        allowed_file_types:
                            - 'image/*'
                        allowed_file_size: '1000000'
                    name: articles_meta_image
            name: articles_meta_conditional_wrapper
            settings:
                allowed_file_types:
                    - ''
                allowed_file_size: ''
            conditions:
                articles_meta_title:
                    event: input
                    receiver_field: articles_meta_description
    storage:
        - node__articles_content
        - node__articles_image
        - node__articles_meta_title
        - node__articles_meta_description
        - node__articles_meta_image
    display_setting:
        articles_content:
            display_label: '1'
            display_as: p
            display_enabled: '1'
        articles_image:
            display_label: '1'
            display_as: image
            display_enabled: '1'
        articles_meta_title:
            display_label: null
            display_as: null
            display_enabled: null
        articles_meta_description:
            display_label: null
            display_as: null
            display_enabled: null
        articles_meta_image:
            display_label: null
            display_as: null
            display_enabled: null
    permission:
        - administrator
        - authenticated
        - manager
        - content_creator
basic_page:
    name: 'Basic page'
    description: 'This is basic page content type'
    machine_name: basic_page
    created: '2025-03-17 11:49 AM'
    fields:
        basic_page_body:
            type: textarea
            label: Body
            required: true
            class:
                - form-control
                - textarea-editor
            default_value: ''
            id: body
            handler: Simp\Default\TextAreaField
            name: basic_page_body
            conditions: {  }
            settings:
                allowed_file_types:
                    - ''
                allowed_file_size: ''
    storage:
        - node__basic_page_body
    permission:
        - authenticated
    display_setting:
        basic_page_body:
            display_label: '1'
            display_as: p
            display_enabled: '1'
