articles:
    name: Articles
    description: 'This is article content type'
    machine_name: articles
    created: '2025-03-13 17:28 PM'
    fields:
        articles_body:
            type: textarea
            label: Body
            required: true
            class:
                - form-control
            default_value: ''
            id: body
            handler: Simp\Default\TextAreaField
            name: articles_body
        articles_image:
            type: file
            label: Image
            required: true
            class:
                - form-control
            default_value: ''
            id: image
            options:
                multiple: multiple
            handler: Simp\Default\FileField
            name: articles_image
    storage:
        - node__articles_body
        - node__articles_image
